version: "3.8"

x-common-config: &common-config
  networks:
    - rabbitmq_go_net
  secrets:
    - DB_USERNAME
    - DB_PASSWORD
    - DB_URI

services:
  app:
    build:
      context: ./api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    env_file:
      - ./api/.env
    depends_on:
      - db
    <<: *common-config
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    <<: *common-config
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: /run/secrets/DB_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: /run/secrets/DB_PASSWORD
      ME_CONFIG_MONGODB_URL: /run/secrets/DB_URI
    <<: *common-config
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    command: >
      sh -c '
        rabbitmq-plugins enable rabbitmq_management;
        rabbitmqctl add_user root root;
        rabbitmqctl set_user_tags root administrator;
        rabbitmqctl set_permissions -p / root ".*" ".*" ".*";
        exec rabbitmq-server '
    <<: *common-config

secrets:
  DB_USERNAME:
    file: ./keys/DB_USERNAME.txt
  DB_PASSWORD:
    file: ./keys/DB_PASSWORD.txt
  DB_URI:
    file: ./keys/DB_URI.txt

networks:
  rabbitmq_go_net:
    driver: bridge