version: "3.8"

x-common-config: &common-config
  networks:
    - rabbitmq_go_net
  env_file:
    - ./.env

services:
  app:
    build:
      context: ./api
    ports:
      - "3000:3000"
    depends_on:
      - db
    <<: *common-config
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongod.conf:/etc/mongod.conf
    command: './configs/init-mongo.sh'
    <<: *common-config
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${DB_URI}
    <<: *common-config
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    command: './configs/init-rabbit.sh'
    <<: *common-config

configs:
  app_config:
    file: ./configs/keys/config.env
  mongo_config:
    file: ./configs/mongod.conf

networks:
  rabbitmq_go_net:
    driver: bridge
    name: rabbitmq_go_net
