# Imagem base
FROM node:16-alpine

# Diretório de trabalho
WORKDIR /usr/src/app

# Copia arquivos necessários
COPY package*.json ./

# Instala dependências
RUN npm install --engine-strict

# Copia o código da aplicação
COPY . .

# Porta que a aplicação irá escutar
EXPOSE 3000

# Comando para iniciar a aplicação
CMD [ "npm", "start" ]
